# Specify the version for docker-compose.yml
version: "20.10"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6c0374FAJRI
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      # POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:C:\Users\fajri\Downloads\Working Jobs\Sirka\Docker

  go:
    container_name: Sirka
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: # create the volume for persisting data.